### ISSUE TITLE
Multiplex options

### ISSUE THREAD

**Issue by iniver** [UIforFreedom/UIF#1]
Hello there
I have been using your nice UIF stably for a few days, and I hope to get a new feature that can permanently save multiplex settings.
Use json to self-add outbound nodes, including multiplex configuration, and can use the multiplex function. Once I edit the node again, the multiplex configuration just lost.
Hoped that developers can add multiplex settings in node templates.
Thanks!

`		"outbounds": [
			{
				"tag": "Initail",
				"protocol": "vless",
				"enabled": false,
				"delay": "",
				"transport": {
					"address": "1.1.1.1",
					"port": 443,
					"protocol": "ws",
					"setting": {
						"path": "/ws",
						"headers": {
							"Host": "web.site"
						}
					},
					"tls_type": "tls",
					"tls": {
						"enabled": true,
						"insecure": false,
						"certificate": "",
						"alpn": [],
						"utls": {
							"enabled": false,
							"fingerprint": "random"
						},
						"disable_sni": false,
						"server_name": "web.site"
					}
				},
				"setting": {
					"uuid": "u-u-i-d",
					"flow": "",
					"multiplex": {
						"enabled": true,
						"protocol": "smux",
						"max_streams": 8,
						"padding": true
					}
				}
			}
		],`

**Comment by JimmyHuang454** [comment]
> Use json to self-add outbound nodes

You can add a node by using UIF self-designed config style but not native Sing-box or V2ray's config. Because, UIF's JSON config be parsed both to Sing-Box and V2ray's config. 

> can permanently save multiplex settings

YES, we will add this feature. And feature that users can determine what internet interface (IPv4 or IPv6) to use on outbounds. 

But at startup time, we hope gettting more feedbacks about Bug to improve UIF's stability. But not just keep adding more feature.

**Comment by UIforFreedom** [comment]
> Use json to self-add outbound nodes

You can add a node by using UIF self-designed config style but not native Sing-box or V2ray's config. Because, UIF's JSON config be parsed both to Sing-Box and V2ray's config.

> can permanently save multiplex settings

YES, we will add this feature. And feature that users can determine what internet interface (IPv4 or IPv6) to use on outbounds.

But at startup time, we hope gettting more feedbacks about Bug to improve UIF's stability. But not just keep adding more feature.
